version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
  build-and-deploy:
    jobs:
      - terraform/fmt:
          checkout: true
          recursive: true
          context: terraform
